# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/scipy23-jupyter-web-app-tutorial',
                'doc_host': 'https://nicole-brewer.github.io',
                'git_url': 'https://github.com/nicole-brewer/scipy23-jupyter-web-app-tutorial',
                'lib_path': 'scipy23_jupyter_web_app_tutorial'},
  'syms': { 'scipy23_jupyter_web_app_tutorial.core': { 'scipy23_jupyter_web_app_tutorial.core.foo': ( 'core.html#foo',
                                                                                                      'scipy23_jupyter_web_app_tutorial/core.py')}}}
